SELECT SOLICITACAOCOMPRA.NR_SOLICITACAO
,COTACAOXSOLICITACAO.NR_COTACAO
,SOLICITACAOCOMPRA.COD_FUNCIONARIO
,SOLICITACAOCOMPRA.DATA
,COALESCE(SOLICITACAOCOMPRA.QTDESOLICITADA,0) AS QTDESOLICITADA
,COALESCE(SOLICITACAOCOMPRA.QTDE_PENDENTE,0) AS QTDE_PENDENTE
,COALESCE(SOLICITACAOCOMPRA.QTDE_APROVACAO,0) AS QTDE_APROVACAO
,SOLICITACAOCOMPRA.COD_MATERIAL
,MATERIAL.DESCRICAO
,SOLICITACAOCOMPRA.OBSERVACAO
,SOLICITACAOCOMPRA.SOLICITACAOAPROVADA
,SOLICITACAOCOMPRA.SOLICITACAOPENDENTE
,SOLICITACAOCOMPRA.SITUACAO
,SOLICITACAOCOMPRA.INFORMACAO_FORNECEDOR
,SOLICITACAOCOMPRA.DATACRIACAO
,APROVACAOPARACOMPRA.DATAAPROVACAO AS APROVACAOCOMPRA
,APROVACAOSOLICITACAOCOMPRA.DATAAPROVACAO AS APROVACAOSOLICITACAO
,SOLICITACAOCOMPRA.COD_ALMOXARIFADO

FROM MATERIAL.SOLICITACAOCOMPRA
,MATERIAL.APROVACAOPARACOMPRA
,MATERIAL.APROVACAOSOLICITACAOCOMPRA
,MATERIAL.MATERIAL
,MATERIAL.COTACAOXSOLICITACAO

WHERE SOLICITACAOCOMPRA.DATA > TO_DATE('01/09/2023','DD/MM/YYYY')
AND SOLICITACAOCOMPRA.COD_ALMOXARIFADO IN ('8','27')
AND APROVACAOPARACOMPRA.NR_SOLICITACAO (+)= SOLICITACAOCOMPRA.NR_SOLICITACAO
AND APROVACAOSOLICITACAOCOMPRA.NR_SOLICITACAO (+)= SOLICITACAOCOMPRA.NR_SOLICITACAO
AND SOLICITACAOCOMPRA.COD_MATERIAL (+)= MATERIAL.COD_MATERIAL
AND COTACAOXSOLICITACAO.NR_SOLICITACAO (+)= SOLICITACAOCOMPRA.NR_SOLICITACAO